//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.Status = "active";
        }
    
        public string IBAN { get; set; }
        public decimal Balance { get; set; }
        public float BonusPoints { get; set; }
        public string AccountType { get; set; }
        public string OwnerPID { get; set; }
        public string Status { get; set; }
    
        public virtual AccountOwner Owner { get; set; }
    }
}
